name: Build Electron App for Windows

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: |
        npm ci --no-audit --no-fund --prefer-offline
        npm run postinstall

    - name: Build for Windows
      run: npm run build:win -- --publish never
      env:
        ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
        ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: electron-chat-app-windows
        path: dist/

  release:
    needs: build-windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Windows build
      uses: actions/download-artifact@v4
      with:
        name: electron-chat-app-windows

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          electron-chat-app-windows/**/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
