name: Build Electron App for Windows

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: |
        npm ci --no-audit --no-fund --prefer-offline
        npm run postinstall

    - name: Build for Windows
      run: npm run build:win -- --publish never
      env:
        ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
        ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder

    - name: List build files
      run: |
        echo "Files in dist directory:"
        dir dist
        echo "Files in current directory:"
        dir

    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: electron-chat-app-windows
        path: dist/*.exe
        retention-days: 30
